### ISSUE TITLE
Suggest and ask

### ISSUE THREAD

**Issue by pengengantibaju** [Sebastian09-09/Anigame-Sniper-Gen-3#3]
How to make spam chat auto delete after few second on spammer.py

**Comment by Jsjnsns78** [comment]
Support for heroku or replit

**Comment by Sebastian09-09** [comment]
> Support for heroku or replit

It already supports both of them... 
if you need help setting them up join the support server

**Comment by Sebastian09-09** [comment]
> How to make spam chat auto delete after few second on spammer.py

the sniper cant do that right now...
